// Mock vocabulary data — HSK 1-3, with English meanings
export const MOCK_VOCAB = [
  {
    id: '1',
    hanzi: '你好',
    pinyin: 'nǐ hǎo',
    meaning: 'Hello / How are you',
    example: '你好，我是小明。(Hello, I am Xiao Ming.)',
    hsk: 1,
    createdAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: '2',
    hanzi: '谢谢',
    pinyin: 'xiè xie',
    meaning: 'Thank you',
    example: '非常谢谢你！(Thank you very much!)',
    hsk: 1,
    createdAt: new Date('2024-01-11').toISOString(),
  },
  {
    id: '3',
    hanzi: '朋友',
    pinyin: 'péng yǒu',
    meaning: 'Friend',
    example: '他是我最好的朋友。(He is my best friend.)',
    hsk: 1,
    createdAt: new Date('2024-01-12').toISOString(),
  },
  {
    id: '4',
    hanzi: '学习',
    pinyin: 'xué xí',
    meaning: 'To study / To learn',
    example: '我每天学习汉语。(I study Chinese every day.)',
    hsk: 1,
    createdAt: new Date('2024-01-13').toISOString(),
  },
  {
    id: '5',
    hanzi: '喜欢',
    pinyin: 'xǐ huān',
    meaning: 'To like / To enjoy',
    example: '我喜欢吃中国菜。(I like eating Chinese food.)',
    hsk: 1,
    createdAt: new Date('2024-01-14').toISOString(),
  },
  {
    id: '6',
    hanzi: '时间',
    pinyin: 'shí jiān',
    meaning: 'Time',
    example: '现在没有时间，对不起。(Sorry, there is no time now.)',
    hsk: 2,
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '7',
    hanzi: '帮助',
    pinyin: 'bāng zhù',
    meaning: 'To help / Help',
    example: '谢谢你帮助我。(Thank you for helping me.)',
    hsk: 2,
    createdAt: new Date('2024-01-16').toISOString(),
  },
  {
    id: '8',
    hanzi: '问题',
    pinyin: 'wèn tí',
    meaning: 'Question / Problem',
    example: '我有一个问题。(I have a question.)',
    hsk: 2,
    createdAt: new Date('2024-01-17').toISOString(),
  },
  {
    id: '9',
    hanzi: '已经',
    pinyin: 'yǐ jīng',
    meaning: 'Already',
    example: '我已经吃饭了。(I have already eaten.)',
    hsk: 2,
    createdAt: new Date('2024-01-18').toISOString(),
  },
  {
    id: '10',
    hanzi: '觉得',
    pinyin: 'jué de',
    meaning: 'To feel / To think',
    example: '我觉得这个很有趣。(I think this is very interesting.)',
    hsk: 2,
    createdAt: new Date('2024-01-19').toISOString(),
  },
  {
    id: '11',
    hanzi: '努力',
    pinyin: 'nǔ lì',
    meaning: 'To work hard / Diligent',
    example: '他学习很努力。(He studies very hard.)',
    hsk: 2,
    createdAt: new Date('2024-01-20').toISOString(),
  },
  {
    id: '12',
    hanzi: '环境',
    pinyin: 'huán jìng',
    meaning: 'Environment / Surroundings',
    example: '我们要保护环境。(We must protect the environment.)',
    hsk: 3,
    createdAt: new Date('2024-01-21').toISOString(),
  },
  {
    id: '13',
    hanzi: '经验',
    pinyin: 'jīng yàn',
    meaning: 'Experience',
    example: '他有很多工作经验。(He has a lot of work experience.)',
    hsk: 3,
    createdAt: new Date('2024-01-22').toISOString(),
  },
  {
    id: '14',
    hanzi: '影响',
    pinyin: 'yǐng xiǎng',
    meaning: 'To influence / Influence',
    example: '天气影响了我们的计划。(The weather influenced our plans.)',
    hsk: 3,
    createdAt: new Date('2024-01-23').toISOString(),
  },
  {
    id: '15',
    hanzi: '完成',
    pinyin: 'wán chéng',
    meaning: 'To complete / To finish',
    example: '我终于完成了这个项目。(I finally completed this project.)',
    hsk: 3,
    createdAt: new Date('2024-01-24').toISOString(),
  },
  {
    id: '16',
    hanzi: '认为',
    pinyin: 'rèn wéi',
    meaning: 'To think / To believe',
    example: '我认为他说的是对的。(I think what he said is correct.)',
    hsk: 3,
    createdAt: new Date('2024-01-25').toISOString(),
  },
  {
    id: '17',
    hanzi: '比较',
    pinyin: 'bǐ jiào',
    meaning: 'Relatively / To compare',
    example: '这里的天气比较热。(The weather here is relatively hot.)',
    hsk: 3,
    createdAt: new Date('2024-01-26').toISOString(),
  },
  {
    id: '18',
    hanzi: '机会',
    pinyin: 'jī huì',
    meaning: 'Opportunity / Chance',
    example: '这是一个很好的机会。(This is a great opportunity.)',
    hsk: 3,
    createdAt: new Date('2024-01-27').toISOString(),
  },
  {
    id: '19',
    hanzi: '重要',
    pinyin: 'zhòng yào',
    meaning: 'Important',
    example: '健康是最重要的事情。(Health is the most important thing.)',
    hsk: 3,
    createdAt: new Date('2024-01-28').toISOString(),
  },
  {
    id: '20',
    hanzi: '发展',
    pinyin: 'fā zhǎn',
    meaning: 'To develop / Development',
    example: '中国经济发展很快。(China\'s economy is developing rapidly.)',
    hsk: 3,
    createdAt: new Date('2024-01-29').toISOString(),
  },
]

export const HSK_LEVELS = [1, 2, 3]

export function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2)
}
