/**
 * pinyinData.js
 * Dữ liệu Hán ngữ Bính âm (Pinyin) chuẩn sư phạm:
 * - 23 Thanh mẫu (Initials) kèm chữ Hán đại diện phát âm chuẩn qua TTS
 * - 24 Vận mẫu cơ bản & mở rộng (Finals) kèm 4 thanh điệu
 * - 5 Thanh điệu (Tones: 1, 2, 3, 4 & khinh thanh) kèm cao độ âm thanh
 * - 5 Quy tắc biến điệu quan trọng (Tone Sandhi)
 * - Ngân hàng câu hỏi trắc nghiệm luyện nghe phân biệt cặp âm dễ nhầm
 */

export const INITIALS = [
  // Âm môi (Lips)
  {
    pinyin: 'b',
    ipa: '[p]',
    name: 'b (bua)',
    speechText: '波', // bō
    soundDemo: 'bō',
    category: 'labial',
    categoryName: 'Âm hai môi',
    vietnameseDesc: 'Gần giống âm "p" nhẹ trong tiếng Việt, không bật hơi, dây thanh không rung mạnh.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Ngậm hai môi lại rồi bật nhẹ ra, phát âm giống "p" trong "pin" nhưng mềm hơn.',
    examples: [
      { hanzi: '爸爸', pinyin: 'bàba', meaning: 'Bố, ba' },
      { hanzi: '八', pinyin: 'bā', meaning: 'Số 8' },
      { hanzi: '杯子', pinyin: 'bēizi', meaning: 'Cái cốc' },
    ],
  },
  {
    pinyin: 'p',
    ipa: '[pʰ]',
    name: 'p (pua - bật hơi)',
    speechText: '坡', // pō
    soundDemo: 'pō',
    category: 'labial',
    categoryName: 'Âm hai môi',
    vietnameseDesc: 'Bật hơi cực mạnh. Khẩu hình giống "b" nhưng dồn hơi từ cổ họng bật tung ra.',
    isAspirated: true,
    isRetroflex: false,
    tips: 'Đặt tờ giấy trước miệng, phát âm "p" tờ giấy phải bay mạnh.',
    examples: [
      { hanzi: '苹果', pinyin: 'píngguǒ', meaning: 'Quả táo' },
      { hanzi: '朋友', pinyin: 'péngyou', meaning: 'Bạn bè' },
      { hanzi: '漂亮', pinyin: 'piàoliang', meaning: 'Xinh đẹp' },
    ],
  },
  {
    pinyin: 'm',
    ipa: '[m]',
    name: 'm (mua)',
    speechText: '摸', // mō
    soundDemo: 'mō',
    category: 'labial',
    categoryName: 'Âm hai môi',
    vietnameseDesc: 'Tương tự âm "m" trong tiếng Việt.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Hai môi khép lại, luồng hơi thoát ra từ khoang mũi.',
    examples: [
      { hanzi: '妈妈', pinyin: 'māma', meaning: 'Mẹ' },
      { hanzi: '猫', pinyin: 'māo', meaning: 'Con mèo' },
      { hanzi: '买', pinyin: 'mǎi', meaning: 'Mua' },
    ],
  },
  {
    pinyin: 'f',
    ipa: '[f]',
    name: 'f (phua)',
    speechText: '佛', // fó
    soundDemo: 'fō',
    category: 'labiodental',
    categoryName: 'Âm răng môi',
    vietnameseDesc: 'Tương tự âm "ph" trong tiếng Việt (phở, phim).',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Răng cửa trên chạm nhẹ vào môi dưới, đẩy luồng hơi ra.',
    examples: [
      { hanzi: '飞机', pinyin: 'fēijī', meaning: 'Máy bay' },
      { hanzi: '饭店', pinyin: 'fàndiàn', meaning: 'Nhà hàng' },
      { hanzi: '分钟', pinyin: 'fēnzhōng', meaning: 'Phút' },
    ],
  },

  // Âm đầu lưỡi (Alveolar)
  {
    pinyin: 'd',
    ipa: '[t]',
    name: 'd (tơ)',
    speechText: '德', // dé
    soundDemo: 'dē',
    category: 'alveolar',
    categoryName: 'Âm đầu lưỡi',
    vietnameseDesc: 'Đọc giống âm "t" trong tiếng Việt (không bật hơi).',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Đầu lưỡi dính chặt vào nướu răng trên, hạ lưỡi nhẹ nhàng phát âm "tưa".',
    examples: [
      { hanzi: '大', pinyin: 'dà', meaning: 'To, lớn' },
      { hanzi: '弟弟', pinyin: 'dìdi', meaning: 'Em trai' },
      { hanzi: '电脑', pinyin: 'diànnǎo', meaning: 'Máy tính' },
    ],
  },
  {
    pinyin: 't',
    ipa: '[tʰ]',
    name: 't (thơ - bật hơi)',
    speechText: '特', // tè
    soundDemo: 'tē',
    category: 'alveolar',
    categoryName: 'Âm đầu lưỡi',
    vietnameseDesc: 'Bật hơi mạnh! Đọc giống âm "th" của tiếng Việt nhưng luồng hơi dứt khoát hơn.',
    isAspirated: true,
    isRetroflex: false,
    tips: 'Đầu lưỡi đặt vào nướu răng trên rồi giật nhanh lùi về, tống hơi ra thật mạnh.',
    examples: [
      { hanzi: '天气', pinyin: 'tiānqì', meaning: 'Thời tiết' },
      { hanzi: '听', pinyin: 'tīng', meaning: 'Nghe' },
      { hanzi: '同学', pinyin: 'tóngxué', meaning: 'Bạn cùng lớp' },
    ],
  },
  {
    pinyin: 'n',
    ipa: '[n]',
    name: 'n (nơ)',
    speechText: '讷', // nè
    soundDemo: 'nē',
    category: 'alveolar',
    categoryName: 'Âm đầu lưỡi',
    vietnameseDesc: 'Tương tự âm "n" trong tiếng Việt.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Đầu lưỡi áp vào chân răng trên, luồng hơi đi qua khoang mũi.',
    examples: [
      { hanzi: '你', pinyin: 'nǐ', meaning: 'Bạn, anh, chị' },
      { hanzi: '女儿', pinyin: 'nǚ\'ér', meaning: 'Con gái' },
      { hanzi: '那', pinyin: 'nà', meaning: 'Kia, đó' },
    ],
  },
  {
    pinyin: 'l',
    ipa: '[l]',
    name: 'l (lơ)',
    speechText: '勒', // lè
    soundDemo: 'lē',
    category: 'alveolar',
    categoryName: 'Âm đầu lưỡi',
    vietnameseDesc: 'Tương tự âm "l" trong tiếng Việt.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Đầu lưỡi cong chạm nướu trên rồi hạ xuống để luồng hơi thoát ra hai bên lưỡi.',
    examples: [
      { hanzi: '老师', pinyin: 'lǎoshī', meaning: 'Giáo viên' },
      { hanzi: '冷', pinyin: 'lěng', meaning: 'Lạnh' },
      { hanzi: '六', pinyin: 'liù', meaning: 'Số 6' },
    ],
  },

  // Âm cuống lưỡi (Velar)
  {
    pinyin: 'g',
    ipa: '[k]',
    name: 'g (cơ/cưa)',
    speechText: '哥', // gē
    soundDemo: 'gē',
    category: 'velar',
    categoryName: 'Âm cuống lưỡi',
    vietnameseDesc: 'Đọc giống âm "c / k" trong tiếng Việt (không bật hơi).',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Gốc lưỡi nâng lên chạm vòm họng mềm rồi nhả nhẹ, phát âm như "cưa".',
    examples: [
      { hanzi: '哥哥', pinyin: 'gēge', meaning: 'Anh trai' },
      { hanzi: '高', pinyin: 'gāo', meaning: 'Cao' },
      { hanzi: '个', pinyin: 'gè', meaning: 'Cái, con (lượng từ)' },
    ],
  },
  {
    pinyin: 'k',
    ipa: '[kʰ]',
    name: 'k (khơ - bật hơi)',
    speechText: '棵', // kē
    soundDemo: 'kē',
    category: 'velar',
    categoryName: 'Âm cuống lưỡi',
    vietnameseDesc: 'Bật hơi mạnh! Gần giống âm "kh" nhưng có tiếng nổ bật ra từ cuống họng.',
    isAspirated: true,
    isRetroflex: false,
    tips: 'Cuống lưỡi chặn luồng hơi rồi bật mạnh hơi ra ngoài từ cuống họng.',
    examples: [
      { hanzi: '看', pinyin: 'kàn', meaning: 'Xem, nhìn' },
      { hanzi: '开', pinyin: 'kāi', meaning: 'Mở' },
      { hanzi: '客气', pinyin: 'kèqi', meaning: 'Khách sáo' },
    ],
  },
  {
    pinyin: 'h',
    ipa: '[x]',
    name: 'h (hưa/khưa nhẹ)',
    speechText: '喝', // hē
    soundDemo: 'hē',
    category: 'velar',
    categoryName: 'Âm cuống lưỡi',
    vietnameseDesc: 'Nằm giữa âm "h" và "kh" nhẹ của tiếng Việt.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Gốc lưỡi tiếp cận vòm miệng mềm, tạo khe hẹp để luồng hơi ma sát thoát ra.',
    examples: [
      { hanzi: '好', pinyin: 'hǎo', meaning: 'Tốt, đẹp' },
      { hanzi: '喝', pinyin: 'hē', meaning: 'Uống' },
      { hanzi: '很', pinyin: 'hěn', meaning: 'Rất' },
    ],
  },

  // Âm mặt lưỡi (Palatal)
  {
    pinyin: 'j',
    ipa: '[tɕ]',
    name: 'j (chi nhẹ)',
    speechText: '鸡', // jī
    soundDemo: 'jī',
    category: 'palatal',
    categoryName: 'Âm mặt lưỡi',
    vietnameseDesc: 'Đọc giống "chi" trong tiếng Việt nhưng dẹt môi và không bật hơi.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Mặt trước của lưỡi nâng lên chạm ngạc cứng (vòm họng trên), mép môi kéo sang hai bên.',
    examples: [
      { hanzi: '家', pinyin: 'jiā', meaning: 'Nhà' },
      { hanzi: '叫', pinyin: 'jiào', meaning: 'Gọi là' },
      { hanzi: '九', pinyin: 'jiǔ', meaning: 'Số 9' },
    ],
  },
  {
    pinyin: 'q',
    ipa: '[tɕʰ]',
    name: 'q (chi - bật hơi)',
    speechText: '七', // qī
    soundDemo: 'qī',
    category: 'palatal',
    categoryName: 'Âm mặt lưỡi',
    vietnameseDesc: 'Bật hơi cực mạnh! Khẩu hình như âm "j" nhưng nén hơi bật tung qua kẽ răng.',
    isAspirated: true,
    isRetroflex: false,
    tips: 'Đặt mặt lưỡi như âm "j", nén hơi lại rồi bật mạnh qua khe giữa mặt lưỡi và ngạc.',
    examples: [
      { hanzi: '去', pinyin: 'qù', meaning: 'Đi' },
      { hanzi: '钱', pinyin: 'qián', meaning: 'Tiền' },
      { hanzi: '请', pinyin: 'qǐng', meaning: 'Xin mời' },
    ],
  },
  {
    pinyin: 'x',
    ipa: '[ɕ]',
    name: 'x (xi)',
    speechText: '西', // xī
    soundDemo: 'xī',
    category: 'palatal',
    categoryName: 'Âm mặt lưỡi',
    vietnameseDesc: 'Đọc giống "x" trong tiếng Việt (xinh, xe) nhưng kéo căng hai khóe môi.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Mặt lưỡi tiếp cận ngạc cứng tạo rãnh hẹp, luồng hơi ma sát nhẹ thoát ra.',
    examples: [
      { hanzi: '谢', pinyin: 'xiè', meaning: 'Cảm ơn' },
      { hanzi: '想', pinyin: 'xiǎng', meaning: 'Muốn, nhớ' },
      { hanzi: '小', pinyin: 'xiǎo', meaning: 'Nhỏ, bé' },
    ],
  },

  // Âm uốn lưỡi (Retroflex) - CỰC QUAN TRỌNG
  {
    pinyin: 'zh',
    ipa: '[ʈʂ]',
    name: 'zh (trư uốn lưỡi)',
    speechText: '知', // zhī
    soundDemo: 'zhī',
    category: 'retroflex',
    categoryName: 'Âm uốn lưỡi (cuộn)',
    vietnameseDesc: 'Uốn cong đầu lưỡi lên vòm họng, phát âm giống "tr" miền Nam, không bật hơi.',
    isAspirated: false,
    isRetroflex: true,
    tips: 'Đầu lưỡi cong lên chạm ngạc cứng, giữ nguyên lưỡi cong khi phát âm.',
    examples: [
      { hanzi: '中国', pinyin: 'Zhōngguó', meaning: 'Trung Quốc' },
      { hanzi: '这', pinyin: 'zhè', meaning: 'Đây, này' },
      { hanzi: '住', pinyin: 'zhù', meaning: 'Sống, ở' },
    ],
  },
  {
    pinyin: 'ch',
    ipa: '[ʈʂʰ]',
    name: 'ch (trư - uốn lưỡi + bật hơi)',
    speechText: '吃', // chī
    soundDemo: 'chī',
    category: 'retroflex',
    categoryName: 'Âm uốn lưỡi (cuộn)',
    vietnameseDesc: 'Vừa uốn cong đầu lưỡi vừa bật hơi cực mạnh! Âm khó nhất đối với người Việt.',
    isAspirated: true,
    isRetroflex: true,
    tips: 'Lưỡi uốn cong như âm "zh", nén hơi lại rồi bật luồng hơi mạnh ra ngoài.',
    examples: [
      { hanzi: '吃', pinyin: 'chī', meaning: 'Ăn' },
      { hanzi: '茶', pinyin: 'chá', meaning: 'Trà' },
      { hanzi: '出租车', pinyin: 'chūzūchē', meaning: 'Xe taxi' },
    ],
  },
  {
    pinyin: 'sh',
    ipa: '[ʂ]',
    name: 'sh (sư uốn lưỡi)',
    speechText: '诗', // shī
    soundDemo: 'shī',
    category: 'retroflex',
    categoryName: 'Âm uốn lưỡi (cuộn)',
    vietnameseDesc: 'Uốn cong đầu lưỡi lên, phát âm giống âm "s" nặng (sao, suối) trong tiếng Việt.',
    isAspirated: false,
    isRetroflex: true,
    tips: 'Đầu lưỡi cong lên gần ngạc cứng (không chạm sát), đẩy luồng hơi ma sát mạnh.',
    examples: [
      { hanzi: '是', pinyin: 'shì', meaning: 'Là' },
      { hanzi: '水', pinyin: 'shuǐ', meaning: 'Nước' },
      { hanzi: '生', pinyin: 'shēng', meaning: 'Sinh, học sinh' },
    ],
  },
  {
    pinyin: 'r',
    ipa: '[ʐ]',
    name: 'r (rư uốn lưỡi)',
    speechText: '日', // rì
    soundDemo: 'rì',
    category: 'retroflex',
    categoryName: 'Âm uốn lưỡi (cuộn)',
    vietnameseDesc: 'Lưỡi uốn cong, phát âm giống "r" tiếng Việt nhưng không rung lưỡi.',
    isAspirated: false,
    isRetroflex: true,
    tips: 'Khẩu hình giống "sh", nhưng làm rung dây thanh âm trong cổ họng.',
    examples: [
      { hanzi: '人', pinyin: 'rén', meaning: 'Người' },
      { hanzi: '热', pinyin: 'rè', meaning: 'Nóng' },
      { hanzi: '认识', pinyin: 'rènshi', meaning: 'Quen biết' },
    ],
  },

  // Âm đầu lưỡi trước (Dental Sibilant)
  {
    pinyin: 'z',
    ipa: '[ts]',
    name: 'z (chư thẳng lưỡi)',
    speechText: '资', // zī
    soundDemo: 'zī',
    category: 'dental',
    categoryName: 'Âm đầu lưỡi trước',
    vietnameseDesc: 'Thẳng lưỡi, đầu lưỡi chạm mặt sau răng trên, đọc như "ch" nhẹ hoặc "tz".',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Không cuộn lưỡi! Cười nhẹ, đặt đầu lưỡi sau răng cửa trên rồi nhả ra nhẹ.',
    examples: [
      { hanzi: '字', pinyin: 'zì', meaning: 'Chữ' },
      { hanzi: '再见', pinyin: 'zàijiàn', meaning: 'Tạm biệt' },
      { hanzi: '早上', pinyin: 'zǎoshang', meaning: 'Buổi sáng' },
    ],
  },
  {
    pinyin: 'c',
    ipa: '[tsʰ]',
    name: 'c (thư thẳng lưỡi - bật hơi)',
    speechText: '疵', // cī
    soundDemo: 'cī',
    category: 'dental',
    categoryName: 'Âm đầu lưỡi trước',
    vietnameseDesc: 'Bật hơi mạnh! Khẩu hình như "z" nhưng đẩy mạnh luồng hơi qua kẽ răng.',
    isAspirated: true,
    isRetroflex: false,
    tips: 'Hai hàm răng khép hờ, lưỡi thẳng, nén hơi tống mạnh qua kẽ răng tạo âm "ts".',
    examples: [
      { hanzi: '菜', pinyin: 'cài', meaning: 'Rau, món ăn' },
      { hanzi: '次', pinyin: 'cì', meaning: 'Lần' },
      { hanzi: '从', pinyin: 'cóng', meaning: 'Từ (đâu đến)' },
    ],
  },
  {
    pinyin: 's',
    ipa: '[s]',
    name: 's (xư thẳng lưỡi)',
    speechText: '思', // sī
    soundDemo: 'sī',
    category: 'dental',
    categoryName: 'Âm đầu lưỡi trước',
    vietnameseDesc: 'Thẳng lưỡi, phát âm giống âm "x" nhẹ trong tiếng Việt.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Lưỡi để thẳng, không cuộn lưỡi, luồng hơi ma sát qua khe răng cửa.',
    examples: [
      { hanzi: '四', pinyin: 'sì', meaning: 'Số 4' },
      { hanzi: '岁', pinyin: 'suì', meaning: 'Tuổi' },
      { hanzi: '三', pinyin: 'sān', meaning: 'Số 3' },
    ],
  },

  // Phụ âm đặc biệt (Semi-vowels)
  {
    pinyin: 'y',
    ipa: '[j]',
    name: 'y (i dài)',
    speechText: '衣', // yī
    soundDemo: 'yī',
    category: 'special',
    categoryName: 'Bán nguyên âm',
    vietnameseDesc: 'Tương đương với nguyên âm "i" đứng đầu âm tiết.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Phát âm như âm "i" kéo dài hoặc "d" nhẹ miền Nam.',
    examples: [
      { hanzi: '一', pinyin: 'yī', meaning: 'Số 1' },
      { hanzi: '衣服', pinyin: 'yīfu', meaning: 'Quần áo' },
      { hanzi: '医院', pinyin: 'yīyuàn', meaning: 'Bệnh viện' },
    ],
  },
  {
    pinyin: 'w',
    ipa: '[w]',
    name: 'w (u)',
    speechText: '屋', // wū
    soundDemo: 'wū',
    category: 'special',
    categoryName: 'Bán nguyên âm',
    vietnameseDesc: 'Tương đương với nguyên âm "u" đứng đầu âm tiết.',
    isAspirated: false,
    isRetroflex: false,
    tips: 'Tròn môi phát âm giống như "u" hoặc "qu" trong tiếng Việt.',
    examples: [
      { hanzi: '我', pinyin: 'wǒ', meaning: 'Tôi, mình' },
      { hanzi: '五', pinyin: 'wǔ', meaning: 'Số 5' },
      { hanzi: '问', pinyin: 'wèn', meaning: 'Hỏi' },
    ],
  },
]

export const FINALS = [
  // Vận mẫu đơn (Simple Finals)
  {
    pinyin: 'a',
    group: 'simple',
    groupName: 'Vận mẫu đơn',
    speechText: '阿',
    tones: ['ā', 'á', 'ǎ', 'à'],
    vietnameseDesc: 'Đọc giống "a" trong tiếng Việt, mở to miệng.',
    tips: 'Miệng mở tự nhiên, lưỡi nằm thấp.',
    sample: 'mā (妈 - mẹ)',
  },
  {
    pinyin: 'o',
    group: 'simple',
    groupName: 'Vận mẫu đơn',
    speechText: '喔',
    tones: ['ō', 'ó', 'ǒ', 'ò'],
    vietnameseDesc: 'Đọc giống "ô" (hoặc "ua" nhẹ khi đi sau b, p, m, f).',
    tips: 'Môi tròn lại, phần gốc lưỡi nâng nhẹ.',
    sample: 'bō (波 - sóng)',
  },
  {
    pinyin: 'e',
    group: 'simple',
    groupName: 'Vận mẫu đơn',
    speechText: '鹅',
    tones: ['ē', 'é', 'ě', 'è'],
    vietnameseDesc: 'Đọc giống "ưa" hoặc "ơ" trong tiếng Việt (không đọc là e).',
    tips: 'Mở hờ miệng, khóe môi hơi kéo sang hai bên như cười mỉm, phát âm "ưa".',
    sample: 'gē (哥 - anh trai)',
  },
  {
    pinyin: 'i',
    group: 'simple',
    groupName: 'Vận mẫu đơn',
    speechText: '衣',
    tones: ['ī', 'í', 'ǐ', 'ì'],
    vietnameseDesc: 'Đọc giống "i" (đọc là "ư" khi đi với zh, ch, sh, r, z, c, s).',
    tips: 'Khi đi với 7 phụ âm z, c, s, zh, ch, sh, r thì i sẽ đọc là "ư".',
    sample: 'nǐ (你 - bạn)',
  },
  {
    pinyin: 'u',
    group: 'simple',
    groupName: 'Vận mẫu đơn',
    speechText: '乌',
    tones: ['ū', 'ú', 'ǔ', 'ù'],
    vietnameseDesc: 'Đọc giống "u" trong tiếng Việt, chu môi.',
    tips: 'Hai môi tròn và nhô về phía trước.',
    sample: 'bù (不 - không)',
  },
  {
    pinyin: 'ü',
    group: 'simple',
    groupName: 'Vận mẫu đơn',
    speechText: '迂',
    tones: ['ǖ', 'ǘ', 'ǚ', 'ǜ'],
    vietnameseDesc: 'Đọc kết hợp giữa "uy" và "u", giữ nguyên môi tròn.',
    tips: 'Khẩu hình tròn môi như phát âm "u", nhưng đầu lưỡi chạm răng dưới phát âm "i".',
    sample: 'yǚ (雨 - mưa)',
  },

  // Vận mẫu kép (Compound Finals)
  {
    pinyin: 'ai',
    group: 'compound',
    groupName: 'Vận mẫu kép',
    speechText: '哀',
    tones: ['āi', 'ái', 'ǎi', 'ài'],
    vietnameseDesc: 'Đọc giống "ai" trong tiếng Việt.',
    tips: 'Bắt đầu từ âm "a" rồi trượt nhanh sang âm "i".',
    sample: 'ài (爱 - yêu)',
  },
  {
    pinyin: 'ei',
    group: 'compound',
    groupName: 'Vận mẫu kép',
    speechText: '诶',
    tones: ['ēi', 'éi', 'ěi', 'èi'],
    vietnameseDesc: 'Đọc giống "ây" trong tiếng Việt.',
    tips: 'Bắt đầu từ âm "e" (ê) rồi chuyển nhanh về âm "i".',
    sample: 'bēi (杯 - cốc)',
  },
  {
    pinyin: 'ui',
    group: 'compound',
    groupName: 'Vận mẫu kép',
    speechText: '威',
    tones: ['uī', 'uí', 'uǐ', 'uì'],
    vietnameseDesc: 'Đọc giống "uây" (viết tắt của uei).',
    tips: 'Chu môi từ âm "u" rồi trượt nhanh qua "ê-i".',
    sample: 'shuǐ (水 - nước)',
  },
  {
    pinyin: 'ao',
    group: 'compound',
    groupName: 'Vận mẫu kép',
    speechText: '熬',
    tones: ['āo', 'áo', 'ǎo', 'ào'],
    vietnameseDesc: 'Đọc giống "ao" trong tiếng Việt.',
    tips: 'Mở miệng phát âm "a" rồi thu tròn môi lại thành "o".',
    sample: 'gāo (高 - cao)',
  },
  {
    pinyin: 'ou',
    group: 'compound',
    groupName: 'Vận mẫu kép',
    speechText: '欧',
    tones: ['ōu', 'óu', 'ǒu', 'òu'],
    vietnameseDesc: 'Đọc giống "âu" trong tiếng Việt.',
    tips: 'Mở khẩu hình vừa phải với "o" rồi thu nhỏ môi lại về "u".',
    sample: 'dǒu (抖 - run)',
  },
  {
    pinyin: 'iu',
    group: 'compound',
    groupName: 'Vận mẫu kép',
    speechText: '优',
    tones: ['iū', 'iú', 'iǔ', 'iù'],
    vietnameseDesc: 'Đọc giống "iêu" (viết tắt của iou).',
    tips: 'Bắt đầu từ "i" và lướt qua "âu/u".',
    sample: 'liù (六 - số 6)',
  },
  {
    pinyin: 'ie',
    group: 'compound',
    groupName: 'Vận mẫu kép',
    speechText: '耶',
    tones: ['iē', 'ié', 'iě', 'iè'],
    vietnameseDesc: 'Đọc giống "iê" (ia) trong tiếng Việt.',
    tips: 'Phát âm "i" rồi mở miệng sang "ê".',
    sample: 'xiè (谢 - cảm ơn)',
  },
  {
    pinyin: 'üe',
    group: 'compound',
    groupName: 'Vận mẫu kép',
    speechText: '约',
    tones: ['üē', 'üé', 'üě', 'üè'],
    vietnameseDesc: 'Đọc giống "uyê" trong tiếng Việt.',
    tips: 'Tròn môi phát âm "ü" rồi mở nhẹ sang "ê".',
    sample: 'yuè (月 - mặt trăng, tháng)',
  },
  {
    pinyin: 'er',
    group: 'compound',
    groupName: 'Vận mẫu kép',
    speechText: '儿',
    tones: ['ēr', 'ér', 'ěr', 'èr'],
    vietnameseDesc: 'Vận mẫu uốn lưỡi đặc biệt, đọc "ơ" + cuộn lưỡi.',
    tips: 'Phát âm "e" (ơ) đồng thời cuộn đầu lưỡi lên vòm họng.',
    sample: 'èr (二 - số 2)',
  },

  // Vận mẫu mũi (Nasal Finals)
  {
    pinyin: 'an',
    group: 'nasal',
    groupName: 'Vận mẫu mũi trước',
    speechText: '安',
    tones: ['ān', 'án', 'ǎn', 'àn'],
    vietnameseDesc: 'Đọc giống "an" trong tiếng Việt.',
    tips: 'Lưỡi chạm nướu trên khi kết thúc âm n.',
    sample: 'sān (三 - số 3)',
  },
  {
    pinyin: 'en',
    group: 'nasal',
    groupName: 'Vận mẫu mũi trước',
    speechText: '恩',
    tones: ['ēn', 'én', 'ěn', 'èn'],
    vietnameseDesc: 'Đọc giống "ân" trong tiếng Việt.',
    tips: 'Phát âm âm "ơ" rồi khép đầu lưỡi vào chân răng trên.',
    sample: 'hěn (很 - rất)',
  },
  {
    pinyin: 'in',
    group: 'nasal',
    groupName: 'Vận mẫu mũi trước',
    speechText: '因',
    tones: ['īn', 'ín', 'ǐn', 'ìn'],
    vietnameseDesc: 'Đọc giống "in" trong tiếng Việt.',
    tips: 'Giữ âm "i" kéo dài rồi đưa luồng hơi qua khoang mũi.',
    sample: 'jīn (今 - nay)',
  },
  {
    pinyin: 'un',
    group: 'nasal',
    groupName: 'Vận mẫu mũi trước',
    speechText: '温',
    tones: ['ūn', 'ún', 'ǔn', 'ùn'],
    vietnameseDesc: 'Đọc giống "uân" (viết tắt của uen).',
    tips: 'Bắt đầu từ "u" rồi chuyển nhanh sang "ân".',
    sample: 'wèn (问 - hỏi)',
  },
  {
    pinyin: 'ün',
    group: 'nasal',
    groupName: 'Vận mẫu mũi trước',
    speechText: '晕',
    tones: ['ǖn', 'ǘn', 'ǚn', 'ǜn'],
    vietnameseDesc: 'Đọc giống "uyn" trong tiếng Việt.',
    tips: 'Tròn môi phát âm "ü" rồi khép đầu lưỡi tạo âm "n".',
    sample: 'yún (云 - mây)',
  },
  {
    pinyin: 'ang',
    group: 'nasal',
    groupName: 'Vận mẫu mũi sau',
    speechText: '昂',
    tones: ['āng', 'áng', 'ǎng', 'àng'],
    vietnameseDesc: 'Đọc giống "ang" trong tiếng Việt, mở to khoang họng.',
    tips: 'Gốc lưỡi nâng lên chạm vòm họng mềm, vang sâu trong họng.',
    sample: 'máng (忙 - bận)',
  },
  {
    pinyin: 'eng',
    group: 'nasal',
    groupName: 'Vận mẫu mũi sau',
    speechText: '鞥',
    tones: ['ēng', 'éng', 'ěng', 'èng'],
    vietnameseDesc: 'Đọc giống "âng" trong tiếng Việt.',
    tips: 'Khởi đầu từ "ơ" rồi cuống lưỡi chặn luồng hơi.',
    sample: 'lěng (冷 - lạnh)',
  },
  {
    pinyin: 'ing',
    group: 'nasal',
    groupName: 'Vận mẫu mũi sau',
    speechText: '鹰',
    tones: ['īng', 'íng', 'ǐng', 'ìng'],
    vietnameseDesc: 'Đọc giống "inh" hoặc "iêng" nhẹ.',
    tips: 'Phát âm "i" kết hợp vang ở cuống họng.',
    sample: 'tīng (听 - nghe)',
  },
  {
    pinyin: 'ong',
    group: 'nasal',
    groupName: 'Vận mẫu mũi sau',
    speechText: '轰',
    tones: ['ōng', 'óng', 'ǒng', 'òng'],
    vietnameseDesc: 'Đọc giống "ung" trong tiếng Việt.',
    tips: 'Tròn môi, gốc lưỡi chạm vòm miệng mềm.',
    sample: 'zhōng (中 - giữa, trung)',
  },
]

export const TONES = [
  {
    id: 1,
    name: 'Thanh 1 (Âm Bình)',
    symbol: '¯ (mā)',
    contour: '55',
    pitchName: 'Cao bằng',
    speechText: '妈',
    soundDemo: 'mā',
    desc: 'Âm thanh giữ ở cao độ tối đa (55), ngân dài đều, không lên không xuống.',
    analogy: 'Như bác sĩ yêu cầu bạn há miệng nói "Aaaa..." thật to và đều giọng.',
    example: { hanzi: '妈 (mā)', meaning: 'Mẹ' },
    color: '#1ed760',
  },
  {
    id: 2,
    name: 'Thanh 2 (Dương Bình)',
    symbol: 'ˊ (má)',
    contour: '35',
    pitchName: 'Lên dốc',
    speechText: '麻',
    soundDemo: 'má',
    desc: 'Bắt đầu ở cao độ trung bình rồi vút nhanh lên cao độ đỉnh (35).',
    analogy: 'Giống như dấu sắc trong tiếng Việt khi bạn ngạc nhiên hỏi: "Hả?", "Gì cơ?".',
    example: { hanzi: '麻 (má)', meaning: 'Mè, cây gai' },
    color: '#539df5',
  },
  {
    id: 3,
    name: 'Thanh 3 (Thượng Thanh)',
    symbol: 'ˇ (mǎ)',
    contour: '214',
    pitchName: 'Xuống rồi lên',
    speechText: '马',
    soundDemo: 'mǎ',
    desc: 'Hạ thấp giọng xuống đáy cổ họng rồi móc nhẹ lên (2-1-4).',
    analogy: 'Gần giống dấu hỏi tiếng Việt nhưng hạ giọng trầm sâu hơn trước khi nâng nhẹ.',
    example: { hanzi: '马 (mǎ)', meaning: 'Con ngựa' },
    color: '#ffa42b',
  },
  {
    id: 4,
    name: 'Thanh 4 (Khứ Thanh)',
    symbol: 'ˋ (mà)',
    contour: '51',
    pitchName: 'Xuống dốc nhanh',
    speechText: '骂',
    soundDemo: 'mà',
    desc: 'Bắt đầu từ đỉnh cao độ (5) rơi thẳng dứt khoát xuống đáy (1). Rất mạnh và ngắn.',
    analogy: 'Như một cú giậm chân dứt khoát hoặc ra lệnh nghiêm nghị: "Không!".',
    example: { hanzi: '骂 (mà)', meaning: 'Mắng mỏ' },
    color: '#f3727f',
  },
  {
    id: 5,
    name: 'Khinh Thanh (Thanh Nhẹ)',
    symbol: '· (ma)',
    contour: '--',
    pitchName: 'Nhẹ và ngắn',
    speechText: '吗',
    soundDemo: 'ma',
    desc: 'Không đánh dấu thanh điệu, đọc lướt nhanh, nhẹ nhàng, ngắn gọn.',
    analogy: 'Như âm đệm cuối câu trong tiếng Việt: "nhé", "hả", "à".',
    example: { hanzi: '吗 (ma)', meaning: 'Trợ từ hỏi (...không?)' },
    color: '#b3b3b3',
  },
]

export const TONE_RULES = [
  {
    id: 'rule-3-3',
    title: '1. Hai Thanh 3 đi liền nhau (3 + 3 → 2 + 3)',
    tag: 'Quy tắc vàng',
    ruleText: 'Khi hai âm tiết mang thanh 3 đứng cạnh nhau, âm tiết thứ nhất bắt buộc biến đổi thành thanh 2 khi phát âm.',
    visualFormula: 'ǎ + ǎ  ➔  á + ǎ',
    examples: [
      {
        written: '你好 (nǐ hǎo)',
        spoken: 'ní hǎo',
        meaning: 'Xin chào',
        audioText: '你好',
      },
      {
        written: '很好 (hěn hǎo)',
        spoken: 'hén hǎo',
        meaning: 'Rất tốt',
        audioText: '很好',
      },
      {
        written: '可以 (kě yǐ)',
        spoken: 'ké yǐ',
        meaning: 'Có thể',
        audioText: '可以',
      },
    ],
    note: 'Lưu ý: Khi viết Pinyin trên sách vở vẫn ghi dấu thanh 3 nguyên bản (nǐ hǎo), nhưng khi đọc thì tự giác biến thành thanh 2 (ní hǎo).',
  },
  {
    id: 'rule-bu',
    title: '2. Biến điệu của chữ "不" (bù)',
    tag: 'Thường gặp nhất',
    ruleText: 'Từ "不" vốn mang thanh 4 (bù). Nhưng khi đứng TRƯỚC một thanh 4 khác, "不" phải đổi thành thanh 2 (bú).',
    visualFormula: 'bù + (thanh 4)  ➔  bú + (thanh 4)',
    examples: [
      {
        written: '不是 (bù shì)',
        spoken: 'bú shì',
        meaning: 'Không phải',
        audioText: '不是',
      },
      {
        written: '不去 (bù qù)',
        spoken: 'bú qù',
        meaning: 'Không đi',
        audioText: '不去',
      },
      {
        written: '不好 (bù hǎo)',
        spoken: 'bù hǎo (giữ nguyên thanh 4 vì "hǎo" là thanh 3)',
        meaning: 'Không tốt',
        audioText: '不好',
      },
    ],
    note: 'Trước thanh 1, 2, 3: giữ nguyên đọc là "bù" (bù gāo, bù lái, bù mǎi).',
  },
  {
    id: 'rule-yi',
    title: '3. Biến điệu linh hoạt của chữ "一" (yī)',
    tag: 'Lưu ý nâng cao',
    ruleText: 'Chữ "一" (yī) đọc thanh 1 khi đứng một mình hoặc là số đếm. Nhưng khi ghép từ sẽ biến đổi theo từ phía sau:',
    visualFormula: 'yī + thanh 4 ➔ yí | yī + thanh 1,2,3 ➔ yì',
    examples: [
      {
        written: '一定 (yī dìng)',
        spoken: 'yí dìng (đổi thành thanh 2 trước thanh 4)',
        meaning: 'Nhất định',
        audioText: '一定',
      },
      {
        written: '一天 (yī tiān)',
        spoken: 'yì tiān (đổi thành thanh 4 trước thanh 1)',
        meaning: 'Một ngày',
        audioText: '一天',
      },
      {
        written: '第一 (dì yī)',
        spoken: 'dì yī (giữ nguyên thanh 1 trong số thứ tự)',
        meaning: 'Thứ nhất',
        audioText: '第一',
      },
    ],
    note: 'Số phòng, số điện thoại: giữ nguyên là thanh 1 (yāo hoặc yī).',
  },
  {
    id: 'rule-u-dots',
    title: '4. Quy tắc bỏ dấu hai chấm của "ü" (ü ➔ u)',
    tag: 'Mẹo chính tả',
    ruleText: 'Khi vận mẫu "ü" kết hợp với các thanh mẫu mặt lưỡi "j, q, x" và bán nguyên âm "y", hai dấu chấm trên đầu "ü" sẽ bị bỏ đi nhưng vẫn phát âm là "ü".',
    visualFormula: 'j / q / x / y + ü  ➔  ju, qu, xu, yu (đọc là uy)',
    examples: [
      {
        written: '去 (qù)',
        spoken: 'đọc tròn môi là "q-ü" chứ không đọc là "cu"',
        meaning: 'Đi',
        audioText: '去',
      },
      {
        written: '月 (yuè)',
        spoken: 'gốc là üè, viết là yuè',
        meaning: 'Tháng, trăng',
        audioText: '月',
      },
      {
        written: '绿 (lǜ) & 女 (nǚ)',
        spoken: 'với "l" và "n" thì PHẢI giữ nguyên 2 chấm để tránh nhầm với "lu, nu"',
        meaning: 'Xanh lá & Phụ nữ',
        audioText: '绿',
      },
    ],
    note: 'Khẩu quyết: "j, q, x, y nhìn thấy ü, búng tay một cái hai chấm bay đi!".',
  },
  {
    id: 'rule-tone-mark',
    title: '5. Thứ tự ưu tiên đặt dấu thanh điệu',
    tag: 'Quy tắc ghi nhớ',
    ruleText: 'Dấu thanh điệu luôn được đánh trên các nguyên nguyên âm (vận mẫu) theo thứ tự ưu tiên cửa miệng mở từ to đến nhỏ.',
    visualFormula: 'a  ➔  o  ➔  e  ➔  i / u (ai sau đánh người đó)  ➔  ü',
    examples: [
      {
        written: 'hǎo',
        spoken: 'Có "a" ưu tiên số 1 ➔ đánh trên a',
        meaning: 'Tốt',
        audioText: '好',
      },
      {
        written: 'liù & guì',
        spoken: '"i" và "u" đi liền nhau thì đánh dấu trên âm đứng sau (liù, guì)',
        meaning: 'Số 6 & Đắt',
        audioText: '六',
      },
    ],
    note: 'Khẩu quyết: "Có a tìm a, không a tìm o, e. Khi i và u song hành, âm nào đứng sau đội mũ".',
  },
]

export const QUIZ_QUESTIONS = [
  {
    id: 1,
    audioText: '坡',
    pinyinAnswer: 'pō',
    category: 'Âm bật hơi (b vs p)',
    options: ['bō', 'pō', 'mō', 'fō'],
    explanation: 'Âm "p" trong Pinyin là âm bật hơi mạnh. Bạn có thể nghe thấy luồng hơi nén và bật bung ra từ hai môi!',
  },
  {
    id: 2,
    audioText: '波',
    pinyinAnswer: 'bō',
    category: 'Âm không bật hơi (b vs p)',
    options: ['pō', 'bō', 'dō', 'gō'],
    explanation: 'Âm "b" đọc như chữ "p" nhẹ của tiếng Việt, tuyệt đối KHÔNG bật hơi.',
  },
  {
    id: 3,
    audioText: '七',
    pinyinAnswer: 'qī',
    category: 'Mặt lưỡi bật hơi (j vs q)',
    options: ['jī', 'qī', 'xī', 'chī'],
    explanation: 'Âm "q" là âm mặt lưỡi bật hơi rất sắc. Lưỡi áp vào vòm miệng trên rồi nén hơi bật mạnh.',
  },
  {
    id: 4,
    audioText: '鸡',
    pinyinAnswer: 'jī',
    category: 'Mặt lưỡi không bật hơi (j vs q)',
    options: ['qī', 'jī', 'zhī', 'zī'],
    explanation: 'Âm "j" đọc nhẹ nhàng giống "chi" trong tiếng Việt, không kèm luồng hơi xì mạnh.',
  },
  {
    id: 5,
    audioText: '吃',
    pinyinAnswer: 'chī',
    category: 'Uốn lưỡi bật hơi (zh vs ch)',
    options: ['zhī', 'chī', 'shī', 'cī'],
    explanation: 'Âm "ch" vừa phải uốn cong đầu lưỡi lên vòm họng vừa phải phóng ra luồng hơi mạnh mẽ!',
  },
  {
    id: 6,
    audioText: '知',
    pinyinAnswer: 'zhī',
    category: 'Uốn lưỡi không bật hơi (zh vs ch)',
    options: ['chī', 'zī', 'zhī', 'jī'],
    explanation: 'Âm "zh" uốn cong đầu lưỡi lên nhưng không bật hơi, nghe như âm "tr" dày dặn.',
  },
  {
    id: 7,
    audioText: '四',
    pinyinAnswer: 'sì',
    category: 'Thẳng lưỡi (s vs sh)',
    options: ['shì', 'sì', 'cì', 'zì'],
    explanation: 'Âm "s" là âm đầu lưỡi trước, giữ lưỡi thẳng phẳng, không cong lưỡi như "sh".',
  },
  {
    id: 8,
    audioText: '是',
    pinyinAnswer: 'shì',
    category: 'Cuộn lưỡi (s vs sh)',
    options: ['sì', 'shì', 'xì', 'cì'],
    explanation: 'Âm "sh" đầu lưỡi phải cuộn cong lên vòm họng, âm dày và có tiếng rít gió ấm.',
  },
  {
    id: 9,
    audioText: '特',
    pinyinAnswer: 'tè',
    category: 'Âm bật hơi (d vs t)',
    options: ['dè', 'tè', 'kè', 'hè'],
    explanation: 'Âm "t" trong tiếng Trung tương đương "th" bật hơi mạnh trong tiếng Việt.',
  },
  {
    id: 10,
    audioText: '德',
    pinyinAnswer: 'dé',
    category: 'Âm không bật hơi (d vs t)',
    options: ['tè', 'dé', 'gè', 'bó'],
    explanation: 'Âm "d" đọc như chữ "t" nhẹ của tiếng Việt, âm chắc và không thoát hơi mạnh.',
  },
  {
    id: 11,
    audioText: '妈',
    pinyinAnswer: 'mā (Thanh 1)',
    category: 'Nhận diện thanh điệu (1 vs 4)',
    options: ['mā (Thanh 1)', 'má (Thanh 2)', 'mǎ (Thanh 3)', 'mà (Thanh 4)'],
    explanation: 'Thanh 1 có cao độ 5-5 cao và ngân phẳng dài đều, không bị tụt giọng.',
  },
  {
    id: 12,
    audioText: '骂',
    pinyinAnswer: 'mà (Thanh 4)',
    category: 'Nhận diện thanh điệu (1 vs 4)',
    options: ['mā (Thanh 1)', 'mà (Thanh 4)', 'má (Thanh 2)', 'ma (Khinh thanh)'],
    explanation: 'Thanh 4 rơi từ cao độ 5 xuống 1 cực kỳ dứt khoát và ngắn, như một tiếng nhấn mạnh.',
  },
  {
    id: 13,
    audioText: '听',
    pinyinAnswer: 'tīng (Vận mẫu mũi sau)',
    category: 'Vận mẫu mũi (in vs ing)',
    options: ['tīn', 'tīng', 'tēn', 'tēng'],
    explanation: 'Vận mẫu "ing" là âm mũi sau (ng), âm vang vọng sâu trong cuống họng.',
  },
  {
    id: 14,
    audioText: '看',
    pinyinAnswer: 'kàn (Vận mẫu mũi trước)',
    category: 'Vận mẫu mũi (an vs ang)',
    options: ['kàng', 'kàn', 'hàn', 'gàn'],
    explanation: 'Vận mẫu "an" kết thúc khi đầu lưỡi chạm vào nướu răng trên, không mở vòm họng như "ang".',
  },
  {
    id: 15,
    audioText: '去',
    pinyinAnswer: 'qù',
    category: 'Quy tắc ü đi với q',
    options: ['cù', 'qù', 'chù', 'kù'],
    explanation: 'Chữ 去 (qù) thực chất là âm "q" kết hợp với vận mẫu tròn môi "ü". Khi viết bỏ 2 chấm nhưng phát âm là "kh-uy".',
  },
]
